---
title: "NOAA_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(plotly)

library(rnoaa)
```



```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Column {data-width=650}
-----------------------------------------------------------------------

### Histogram

```{r}
gghist <- ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)

ggplotly(gghist)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot

```{r}
ggbox <- ggplot(weather_df, aes(x = name, y = tmax, fill = name)) + 
  geom_boxplot()

ggplotly(ggbox)
```


### Scatter

```{r}
gg_scatter <- ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)

ggplotly(gg_scatter)

```

